### ISSUE TITLE
 Incorrect URL

### ISSUE THREAD

**Issue by filipefreitasdasilva** [udacity/andfun-kotlin-gdg-finder#13]
In the "GdgApiService.kt" file, the base URL is incorrect.  This URL should be "https://developers.google.com/community/gdg/groups/"

**Comment by Zingam** [comment]
This causes and exception in retrofit2

**Comment by nimaiwalsh** [comment]
Thanks mate, the updated URL works.

**Comment by Gene-R-Pool** [comment]
If you point a browser to https://developers.google.com/community/gdg/directory/ it redirects to https://developers.google.com/community/gdg/groups.
It took me longer than I would like to admit to notice that. I kept getting a 404 in the app but, the browser loaded it just fine.

**Comment by Andre-max** [comment]
Working solution in #17
