### ISSUE TITLE
Starter code - Android resource linking failed

### ISSUE THREAD

**Issue by lswitaj** [udacity/andfun-kotlin-gdg-finder#19]
`AAPT: error: resource array/preloaded_fonts (aka com.example.android.gdgfinder:array/preloaded_fonts) not found.`

**Comment by lswitaj** [comment]
I've removed the following line from `AndroidManifest.xml` and it works now:
`<meta-data android:name="preloaded_fonts" android:resource="@array/preloaded_fonts"/>`

**Comment by jzagoli** [comment]
same

**Comment by prokopCerny** [comment]
Issue still present

**Comment by adrianpbv** [comment]
I've faced the same problem and found a solution [in the official doc](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts#predeclaring-fonts)

**Comment by nakvanna** [comment]
Create an preloaded_fonts.xml resource file within res/values with the following code

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <array name="preloaded_fonts" translatable="false">
        <item>@font/font1</item>
    </array>
</resources>

Replace font1 with your font
