### ISSUE TITLE
Crash when try to open GdgListFragment with 404 error

### ISSUE THREAD

**Issue by Daracul** [udacity/andfun-kotlin-gdg-finder#4]
That's becouse site https://developers.google.com/community/gdg/gdg-directory.json don't work. It shows 404 error. Please fix it

**Comment by HemanshuVarma** [comment]
@Daracul Use this instead 
_https://developers.google.com/community/gdg/directory/directory.json_

**Comment by TheKrushik** [comment]
> @Daracul Use this instead
> _https://developers.google.com/community/gdg/directory/directory.json_

Does not work

**Comment by HemanshuVarma** [comment]
Hey @TheKrushik, It was working perfectly before but with recent upgradation in their website the URL is little modified.

Use this URL instead
_https://developers.google.com/community/gdg/groups/directory.json_

Thanks!

**Comment by lidaamber** [comment]
BaseURL to make it work should be https://developers-dot-devsite-v2-prod.appspot.com/community/gdg/groups/

**Comment by xueluwei** [comment]
> BaseURL to make it work should be https://developers-dot-devsite-v2-prod.appspot.com/community/gdg/groups/

not work

**Comment by Andre-max** [comment]
@xueluwei Working solution at #17

**Comment by SudKul** [comment]
The URL has now changed to https://gdg.community.dev/api/ and the endpoint to @GET("chapter_region?chapters=true"). We are working to fix the affected code.
