### ISSUE TITLE
Json object page 404 error

### ISSUE THREAD

**Issue by ignaciosalia** [udacity/andfun-kotlin-gdg-finder#5]
This https://developers.google.com/community/gdg/data/ is down and doesn't return the object gdg-directory.json can the link is incorrect or region lock I'm in México City, some else has try in different region ?

**Comment by HemanshuVarma** [comment]
Heyy @ignaciosalia 
Upon looking into code i found the URL for the json
_https://developers.google.com/community/gdg/directory/directory.json_
Hope it helps :raised_hands:

**Comment by ignaciosalia** [comment]
Hi Thank you 
I will test it and let it you know if it work

**Comment by ignaciosalia** [comment]
It work perfect again thank you
