### ISSUE TITLE
GDG List URL is 404

### ISSUE THREAD

**Issue by aleksinthecloud** [udacity/andfun-kotlin-gdg-finder#8]
https://github.com/udacity/andfun-kotlin-gdg-finder/blob/final/app/src/main/java/com/example/android/gdgfinder/network/GdgApiService.kt

The link to the list of GDGs has changed. The old link gives a 404. The list is now here: https://developers.devsite.corp.google.com/community/gdg/groups/directory.json

- Aleks

**Comment by mayokunthefirst** [comment]
> https://github.com/udacity/andfun-kotlin-gdg-finder/blob/final/app/src/main/java/com/example/android/gdgfinder/network/GdgApiService.kt
> 
> The link to the list of GDGs has changed. The old link gives a 404. The list is now here: https://developers.devsite.corp.google.com/community/gdg/groups/directory.json
> 
> * Aleks

Just ran into this error as I was getting an error 404. Thanks for the update. 👍

**Comment by mdrahil** [comment]
> https://github.com/udacity/andfun-kotlin-gdg-finder/blob/final/app/src/main/java/com/example/android/gdgfinder/network/GdgApiService.kt
> 
> The link to the list of GDGs has changed. The old link gives a 404. The list is now here: https://developers.devsite.corp.google.com/community/gdg/groups/directory.json
> 
> * Aleks

Not Working.
The new URL requires an SSO login and is only meant for internal use.

**Comment by aleksinthecloud** [comment]
A redirect has been implemented so that the original URL is not broken anymore.

**Comment by michaelu123** [comment]
The redirect does not seem to work, and the new URL asks for SSO credentials

**Comment by michaelu123** [comment]
The redirect with the original URL does not work. The URL with devsite.corp.google asks for SSO credentials. The URL given by mayokunthefist works. In GdgApiService.kt set 
`private const val BASE_URL = "https://developers.google.com/community/gdg/groups/"
`

**Comment by wr200m** [comment]
https://developers.google.com/community/gdg/groups/directory.json

This link just became 404 again this afternoon. It was okay earier today.

**Comment by betabloch** [comment]
I have the same issue now - can't complete the new module because can't find the base url for my json

**Comment by xueluwei** [comment]
same issue now. also can't finish this class

**Comment by TobiasDemoor** [comment]
same issue here

**Comment by gabriel7771** [comment]
Same issue
